version: '3'

services:
  mariadb:
    image: 'mariadb:10.11'
    ports:
      - '3307:3306'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'